module.exports = {
  purge: {
    content: ['./src/pages/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}'],
    safelist: [
      'bg-gray-200',
      'bg-gray-300',
      'bg-red-300',
      'bg-yellow-300',
      'bg-green-300',
      'bg-blue-300',
      'bg-indigo-300',
      'bg-purple-300',
      'bg-pink-300',
      'bg-gray-300',
      'bg-red-300',
      'bg-yellow-300',
      'bg-green-300',
      'bg-blue-300',
      'bg-indigo-300',
      'bg-purple-300',
      'bg-pink-300',
      'bg-red-300',
      'bg-yellow-300',
      'bg-green-300',
      'lg:absolute',
      'lg:top-6',
      'lg:right-8',
      'lg:mt-12',
      'lg:mb-4',
      'lg:mb-0 ',
      'p-8',
      'py-2',
      'text-gray-50',
      'rounded-xl',
      'text-3xl',
      'lg:pt-16',
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [require('@tailwindcss/line-clamp'), 'postcss-import', 'tailwindcss', 'autoprefixer'],
}
